# Generated by Django 4.1.7 on 2023-03-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_app', '0002_devices_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
